build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.20-alpine
  amd64: ghcr.io/home-assistant/amd64-base:3.20-alpine
  armhf: ghcr.io/home-assistant/armhf-base:3.20-alpine
  armv7: ghcr.io/home-assistant/armv7-base:3.20-alpine
  i386: ghcr.io/home-assistant/i386-base:3.20-alpine
